# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CBRNHNMemplexMET
                                 A QGIS plugin
 This plugin add the Memplex MET as layers
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-06-10
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Sören Wirries
        email                : soeren@swirries.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QVariant,QDateTime
from qgis.PyQt.QtGui import QIcon, QColor
from qgis.PyQt.QtWidgets import QAction, QApplication
from qgis.core import Qgis, QgsVectorLayer, QgsFeature, QgsField, QgsGeometry, QgsPointXY, QgsProject, QgsDistanceArea, QgsLayerTreeLayer
import re
import math
from datetime import datetime
import configparser
import os.path

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .cbrn_hn_memplex_met_dialog import CBRNHNMemplexMETDialog
from .maptool import PointTool

class CBRNHNMemplexMET:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'CBRNHNMemplexMET_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&CBRN Memplex MET')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('CBRNHNMemplexMET', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/cbrn_hn_memplex_met/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Import MEMPLEX MET'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&CBRN Memplex MET'),
                action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = CBRNHNMemplexMETDialog()
            self.dlg.finished.connect(self.result)
            self.dlg.file_input.setFilter("*.txt;;*.*")
            self.dlg.file_input.setFilePath("")
            self.dlg.start_point.setText("")
            self.dlg.map_button.setIcon(QIcon(":images/themes/default/cursors/mCapturePoint.svg"))
            self.dlg.map_button.clicked.connect(self._on_map_click)
            self.dlg.spread_type.clear()
            self.dlg.spread_type.addItems(["Sofortige Freisetzung", "Lachenverdampfung", "Kontinuierliche Freisetzung"])
            self.dlg.user_datetime.setDateTime(QDateTime.currentDateTime())
            
            # set values from config
            config = configparser.ConfigParser()
            config.read(os.path.join(os.path.dirname(__file__), "config.ini"))
            
            self.dlg.vehicle.setText(config['DEFAULT'].get('vehicle'))
            self.dlg.file_input.setFilePath(config['DEFAULT'].get('met_path'))

            if config['DEFAULT'].getboolean('demo'):
                self.dlg.editor.setText(config['DEMO'].get('editor'))
                self.dlg.location.setText(config['DEMO'].get('location'))
                self.dlg.number.setText(config['DEMO'].get('number'))
                self.dlg.start_point.setText(config['DEMO'].get('start'))
        # show the dialog
        self.dlg.open()

    
    def _on_map_click(self):
        self.dlg.hide()
        self.point_tool = PointTool(self.iface.mapCanvas())
        self.iface.mapCanvas().setMapTool(self.point_tool)
        self.point_tool.canvasClicked.connect(self._write_line_widget)
    
    def _write_line_widget(self, point: QgsPointXY):
        self.dlg.start_point.setText(f"{point.x():.6f},{point.y():.6f}")
        self.iface.mapCanvas().unsetMapTool(self.point_tool)
        self.dlg.show()
        self.point_tool.deactivated.connect(lambda: QApplication.restoreOverrideCursor())
    
    def result(self, result: int):
        if result:  
            vectorLayer = None
            dataProvider = None
            listOfPoints = []
            colorRegex = re.compile("[^a-z0-9]+")
            dictOfLayer = {}
            distanceArea = QgsDistanceArea()
            distanceArea.setEllipsoid("WGS84")
            colorDict = {
                "geruchsgrenze":[0,128,128],
                "ex50ueg":[255,0,0],
                "imhaus":[255,20,147],
                "imfreien":[255,182,193],
                "wolkenexplosionohr":[218,165,32], 
                "wolkenexplosionglasbruch":[255,255,0], 
                "tankexplosionohr": [101,67,33],
                "tankexplosionglasbruch": [210,105,30],
                "tankexplosionfragmente": [255,127,80],
                "tankexplosiontuberockets": [255,127,0],
                "bleve1grad": [135,206,235],
                "bleve2grad": [106,90,205],
                "bleveholz": [65,105,225],
            }
            # user inputs     
            filename = self.dlg.file_input.filePath()
            startingPoint = self.dlg.start_point.text()
            windDirection = self.dlg.wind_direction.text()
            colorAlphaPercentage = self.dlg.color_alpha_percent.value()

            inputVehicle = self.dlg.vehicle.text()
            inputEditor = self.dlg.editor.text()
            inputLocation = self.dlg.location.text()
            inputNumber = self.dlg.number.text()
            inputSpreadType = self.dlg.spread_type.currentText()
            inputTime = self.dlg.user_datetime.dateTime().toString("dd.MM.yyyy HH:mm:ss")

            colorAlpha = int(255 * (int(colorAlphaPercentage) / 100))
            
            startingPoints = startingPoint.split(",")
            startLat = float(startingPoints[1])
            startLon = float(startingPoints[0])
            angleCorrection = (float(windDirection) - 270) / 180 * math.pi
            
            file = open(filename, "r")
            #print(file.read())
            self.iface.messageBar().pushMessage(
                "Loading", "Importing file " + filename,
                level=Qgis.Info, duration=6)
            for line in file:
                if re.match("LABEL:.?", line):
                    if not (vectorLayer is None):
                        fet = QgsFeature()
                        fet.setGeometry(QgsGeometry.fromPolygonXY([listOfPoints]))
                        dataProvider.addFeatures( [fet] )
                        colorName = colorRegex.sub("",pointsName.lower()) 
                        rgbColors = colorDict[colorName]
                        vectorLayer.renderer().symbol().symbolLayer(0).setColor(QColor(rgbColors[0],rgbColors[1],rgbColors[2],colorAlpha))
                        vectorLayer.commitChanges()
                        dictOfLayer[distanceArea.measureArea(fet.geometry())] = vectorLayer
                        listOfPoints = []

                    pointsName = line[7:].strip()
                    vectorLayer = QgsVectorLayer("Polygon", pointsName, "memory")
                    dataProvider = vectorLayer.dataProvider()
                    vectorLayer.startEditing()

                if re.match("(-?[0-9.]+)\t(-?[0-9.]+)", line):
                    metPoints = line.split("\t")
                    east = float(metPoints[0])
                    north = float(metPoints[1])

                    if abs(east) < 1 or abs(north) < 1:
                        continue

                    angle = math.atan(north / east)
                    # dist = east / cos(angle)
                    distance = east / math.cos(angle)
                    # distlat = dist * cos(angle)
                    distLat = distance * math.cos(angle + angleCorrection)
                    # distLon = dist * sin(angle)
                    distLon = distance * math.sin(angle + angleCorrection)
                    # distLatOffset = distLat / 1850
                    distLatOffset = distLat / 1850.0
                    # northAnlge = PI * lat / 180
                    northAngle = math.pi * startLat / 180.0
                    # distLonOffset = distLon / (1850 * cos(northAngle)
                    distLonOffset = distLon / (1850.0 * math.cos(northAngle))
                    # newLat = lat + distLatOffset/ 60
                    lat = startLat + distLatOffset / 60.0
                    # newLon = lon + distLonOffset / 60
                    lon = startLon + distLonOffset / 60.0
                    # print(lat, lon)
                    listOfPoints.append(QgsPointXY(lon,lat))
            # close the file after reading
            file.close()
            # last layer
            fet = QgsFeature()
            fet.setGeometry(QgsGeometry.fromPolygonXY([listOfPoints]))
            dataProvider.addFeatures( [fet] )
            # get the color of the layer
            colorName = colorRegex.sub("",pointsName.lower())
            rgbColors = colorDict[colorName]
            # set layer color
            vectorLayer.renderer().symbol().symbolLayer(0).setColor(QColor(rgbColors[0],rgbColors[1],rgbColors[2],colorAlpha))
            vectorLayer.commitChanges()
            # calc area of spread for sporting
            dictOfLayer[distanceArea.measureArea(fet.geometry())] = vectorLayer
            
            # set start point
            importDateTime =  datetime.now()

            pointLayer = QgsVectorLayer("Point", "Start", "memory")
            pointDataProvider = pointLayer.dataProvider()
            pointLayer.startEditing()
            pointDataProvider.addAttributes([
                QgsField("Fahrzeug",QVariant.String),
                QgsField("Bearbeiter",QVariant.String),
                QgsField("Adresse / Einsatzort",QVariant.String),
                QgsField("Einsatznummer",QVariant.String),
                QgsField("Art der Freisetzung",QVariant.String),
                QgsField("Datum / Uhrzeit",QVariant.String),
                ])
            pointLayer.updateFields()
            fet = QgsFeature(pointLayer.fields())
            fet["Fahrzeug"] = inputVehicle
            fet["Bearbeiter"] = inputEditor
            fet["Adresse / Einsatzort"] = inputLocation
            fet["Einsatznummer"] = inputNumber
            fet["Art der Freisetzung"] = inputSpreadType
            fet["Datum / Uhrzeit"] = inputTime
            fet.setGeometry(QgsGeometry.fromPointXY(QgsPointXY(startLon, startLat)))
            pointDataProvider.addFeatures( [fet] )
            pointLayer.renderer().symbol().symbolLayer(0).setColor(QColor(0,0,0,255))
            pointLayer.commitChanges()
            dictOfLayer[0] = pointLayer

            # sorting and add to project
            layerRoot = QgsProject.instance().layerTreeRoot()
            dt_string = importDateTime.strftime("%Y-%m-%d_%H-%M-%S")
            metGroup = layerRoot.insertGroup(0,"MET_"+dt_string)

            for key in sorted(dictOfLayer.keys(), reverse=True):
                QgsProject.instance().addMapLayer(dictOfLayer[key], False)
                metGroup.insertChildNode(0, QgsLayerTreeLayer(dictOfLayer[key]))

            self.iface.messageBar().pushMessage(
                "Success", "Imported " + filename,
                level=Qgis.Success, duration=3)

    pass